name: Kernel Build

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with: 
        fetch-depth: 0

    - name: Initialization environment
      run: |
        sudo apt update
        sudo apt install -y openssl ccache bc bash libdebuginfod-dev git gnupg build-essential zip curl make automake autogen autoconf autotools-dev libtool shtool python3 python-is-python3 m4 gcc libtool zlib1g-dev flex gcc-aarch64-linux-gnu libssl-dev
        
    - name: Download Clang
      run: |
        mkdir ~/cbl
        wget https://dl.akr-developers.com/?file=CBL/Candy_clang-20201120.tar.zst
        tar -I zstd -xvf Candy_clang-20201120.tar.zst -C ~/cbl

    - name: Build Kernel
      run: |
        ls
        sh build.sh

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')

    - name: Check space usage
      if: (!cancelled())
      run: df -hT
